print('hello')
name=input('what\'s you name :').strip()
print('Hello ',name)
print('numbers')
age=input('your age ?:').strip()
print(age)
print('Welcome')

print('adding new line after editing in growth branch, but not pulled')
print('added line in growth branch')
print('hmm')
print('diff change at local')
print('test branch')